os: linux
dist: bionic
sudo: required

env:
  jobs:
  - TEST_TARGET: test-debian
  - TEST_TARGET: test-alpine
  - TEST_TARGET: test-mainline
  - TEST_TARGET: test-mainline-alpine

before_install:
  - sudo apt-get -y remove docker docker-engine docker-ce
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - sudo apt-get install -y qemu-user-static binfmt-support qemu-kvm qemu-user qemu-system-* 
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multibuilder
  - docker buildx use multibuilder
  - docker buildx inspect --bootstrap
  - docker buildx ls
  - docker version
  - docker info
  # prepare docker test requirements
  - make update-dependencies

script:
  - sudo bash ./check-qemu.sh
  - make $TEST_TARGET

jobs:
  include:
    - stage: deploy
      if: branch = master && NOT type = pull_request
      script:
        - curl -X 'POST' ${DOCKER_CALLBACK_TRIGGER} > /dev/null 2>&1
